# pubspec.yaml (프로젝트 루트)
name: offsub
description: 구독 관리 앱 - 오프서브
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  smooth_page_indicator: ^1.2.0
  shared_preferences: ^2.3.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
